In [9]:
cd Downloads

/Users/andrewyaspan/Downloads

In [332]:
import pandas as pd
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 500)

In [181]:
sf = pd.read_excel('SF_JobsReport.xls')

In [333]:
sf

,Employer,Job Title,Hourly Wage,Hours / Week,Status,Benefits,Placement Type,Start Date,Term. Date,Unnamed: 9,Unnamed: 10,exp
0,Placed into Employment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Corner Bakery
1,"Alex, Duran SSN: 318-82-2799 Case: 12249...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Walmart
2,Corner Bakery,cook,10,40.0,Full-Time,Yes,Unsubsidized,2016-11-14 00:00:00,2016-11-14 00:00:00,11.00,1.0,The Ark
3,"Alvarez, Eugene SSN: 361-08-5657 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Luster Products
4,Walmart,Sales Associate,10,40.0,Full-Time,No,Unsubsidized,2016-09-05 00:00:00,00:00:00,9.00,2.0,Walgreens
5,"Bosley, Fake SSN: Case: 12238 Progr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
6,The Ark,NaN,10.5,0.0,NaN,NaN,NaN,2016-12-16 00:00:00,00:00:00,12.00,3.0,Greater West Town
7,"Bradley, Reginald SSN: 361-88-4414 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
8,Luster Products,loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,2016-12-15 00:00:00,9.00,4.0,LBP Manufacturing
9,Walgreens,CLERK,10,20.0,Part-Time,No,NaN,2017-03-22 00:00:00,00:00:00,3.00,5.0,Swisssport
10,"Butler, Marcus SSN: 321-94-9369 Case: 12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Studio Movie
11,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,6.0,Saint Sabina ERC
12,"Cathery, Daquan SSN: 344-90-0317 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
13,Greater West Town,intern,10,15.0,Seasonal,No,Subsidized,2017-02-20 00:00:00,00:00:00,2.00,7.0,LA Fitness
14,"Cattron, Raymond SSN: 326-80-5542 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Macy's
15,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,8.0,Luster Products
16,"Davis, Antonio SSN: 351-40-8095 Case: 11...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
17,LBP Manufacturing,NaN,11.25,40.0,Full-Time,NaN,Unsubsidized,2016-08-01 00:00:00,2016-09-02 00:00:00,8.00,9.0,Unemployed
18,Swisssport,Sorter,10,40.0,Full-Time,Yes,Unsubsidized,2017-01-30 00:00:00,2017-03-03 00:00:00,1.00,10.0,Unemployed
19,Studio Movie,Greeter,12.35,40.0,Full-Time,No,Unsubsidized,2017-03-03 00:00:00,00:00:00,3.00,11.0,Walgreens
20,"Davis, Gregory SSN: 352-88-5473 Case: 12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,LA Fitness
21,Saint Sabina ERC,Youth Counselor,10,40.0,Full-Time,No,Unsubsidized,2016-11-14 00:00:00,00:00:00,11.00,12.0,Hinkley Springs
22,"Evans, Dennis SSN: 298-96-3303 Case: 123...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Luster Products
23,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,13.0,Walmart
24,"Gallardo, Fake SSN: Case: 12236 Pro...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dollar Tree
25,LA Fitness,Program Manager,10,0.0,Full-Time,No,Unsubsidized,2016-05-23 00:00:00,00:00:00,5.00,14.0,The Ark
26,"Goshay, Titus SSN: 344-86-1798 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The Ark
27,Macy's,Asset Protection,10,40.0,Full-Time,No,Unsubsidized,2016-12-20 00:00:00,00:00:00,12.00,15.0,Uber
28,"Greenwood, Demitris SSN: 334-92-0519 Case...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
29,Luster Products,Loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,00:00:00,9.00,16.0,Macy's
30,"Harris, Michael SSN: 359-82-9655 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dollar Tree
31,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,17.0,EA Sween
32,"Hill, Andre SSN: 339-92-4371 Case: 12248...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
33,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,18.0,Norman's Bistro
34,"Hill, Pierre SSN: 324-90-9875 Case: 1225...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,C.H. Robinson
35,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,19.0,Paul Cuffe
36,"Hughes, Corey SSN: 340-78-0840 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Luster Products
37,Walgreens,Stock Worker,10,25.0,Part-Time,No,Subsidized,2016-09-12 00:00:00,00:00:00,9.00,20.0,St. Sabina Employment Resource Center
38,"Jackson, Cornelius SSN: 349-82-4041 Case:...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
39,LA Fitness,NaN,11,0.0,Part-Time,NaN,Unsubsidized,2016-09-16 00:00:00,00:00:00,9.00,21.0,Unemployed
40,"Jacksonl, Darrell SSN: 340-94-7457 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,St. Sabina Employment Resource Center
41,Hinkley Springs,Assembly Line,11,40.0,Full-Time,Yes,Unsubsidized,2016-09-20 00:00:00,2017-01-20 00:00:00,9.00,22.0,LA Fitness
42,"James, Frederick SSN: 333-80-9485 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
43,Luster Products,Fork Lift,11,40.0,Full-Time,Yes,Subsidized,2016-11-21 00:00:00,00:00:00,11.00,23.0,Metraflex
44,"Jones, Shimund SSN: 344-94-9943 Case: 12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
45,Walmart,Clerk,10,40.0,Full-Time,No,Unsubsidized,2016-10-10 00:00:00,00:00:00,10.00,24.0,Greater West Town
46,"Lanier, Torrance SSN: 329-92-2665 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
47,Dollar Tree,Clerk,11,40.0,Full-Time,No,Unsubsidized,2016-12-05 00:00:00,00:00:00,12.00,25.0,Mellow Yellow
48,"Lee, Fake SSN: 343-66-9894 Case: 1212 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Dunkin Donuts
49,The Ark,Manager,15.5,80.0,Full-Time,Yes,NaN,2016-12-16 00:00:00,00:00:00,12.00,26.0,Unemployed
50,The Ark,NaN,0,0.0,NaN,NaN,NaN,2016-12-16 00:00:00,00:00:00,12.00,27.0,Kia Auto
51,"Mapp, Jovan SSN: 340-84-2022 Case: 12253...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Walgreens
52,Uber,driver,12,40.0,Full-Time,No,Unsubsidized,2016-09-19 00:00:00,2017-01-31 00:00:00,9.00,28.0,The Ark
53,"Miller, Deshawn SSN: 327-86-5679 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Macy's
54,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-01-13 00:00:00,00:00:00,1.00,29.0,Walgreens
55,Macy's,Asset Protection,10,40.0,Seasonal,No,Unsubsidized,2016-12-05 00:00:00,2017-01-20 00:00:00,12.00,30.0,Luster Products
56,Dollar Tree,clerk,10,25.0,Part-Time,No,Unsubsidized,2017-03-22 00:00:00,00:00:00,3.00,31.0,Luster Products
57,"Myles, Charmichael SSN: 323-86-7977 Case:...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,S & C Electric
58,EA Sween,Driver,11.5,40.0,Full-Time,Yes,Unsubsidized,2016-10-17 00:00:00,00:00:00,10.00,32.0,Peacocks Foods
59,"O'Neal, Mario SSN: 320-86-8036 Case: 119...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fake Employer 6
60,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,33.0,Fake Employer 7
61,"O'Neal, Quentin SSN: 357-88-1443 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unemployed
62,Norman's Bistro,Waiter,8.5,25.0,Part-Time,No,Unsubsidized,2016-06-16 00:00:00,00:00:00,6.00,34.0,Total for :Placed into Employment
63,"Owens, Jonathan SSN: 340-90-5288 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Total Participants
64,C.H. Robinson,Dispatcher,13,40.0,Full-Time,Yes,Unsubsidized,2016-09-09 00:00:00,00:00:00,9.00,35.0,NaN
65,"Parham, Roushan SSN: 357-92-3591 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Paul Cuffe,Youth Counselor,12.86,20.0,Part-Time,No,Unsubsidized,2017-01-23 00:00:00,00:00:00,1.00,36.0,NaN
67,"Pegues, Garren SSN: 333-94-3352 Case: 12...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
68,Luster Products,Loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,2016-11-18 00:00:00,9.00,37.0,NaN
69,"Porche, Al SSN: 327-86-0336 Case: 12285 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
70,St. Sabina Employment Resource Center,Youth Counselor,10,40.0,Full-Time,No,Subsidized,2016-12-05 00:00:00,00:00:00,12.00,38.0,NaN
71,"Porter-Smith, Allen SSN: 360-02-9637 Case...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,39.0,NaN
73,"Powell, Larry SSN: 355-80-6697 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,40.0,NaN
75,"Ray, Torey SSN: 393-11-5101 Case: 11995 ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,St. Sabina Employment Resource Center,Receptionist,10,35.0,Full-Time,NaN,Unsubsidized,2016-11-16 00:00:00,00:00:00,11.00,41.0,NaN
77,"Redmond, Mark SSN: 338-92-5721 Case: 119...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,LA Fitness,NaN,10.5,0.0,Part-Time,NaN,Unsubsidized,2016-10-08 00:00:00,00:00:00,10.00,42.0,NaN
79,"Reynolds, Nelson SSN: 352-90-5819 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,43.0,NaN
81,"Richardson, Rashad SSN: 350-86-9747 Case:...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,Metraflex,NaN,10,40.0,Seasonal,No,Subsidized,2016-09-15 00:00:00,2016-12-16 00:00:00,9.00,44.0,NaN
83,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,45.0,NaN
84,"Sanderson, Robert SSN: 331-88-7598 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,Greater West Town,intern,10,15.0,Part-Time,No,Subsidized,2017-01-30 00:00:00,00:00:00,1.00,46.0,NaN
86,"Stroman, Ibrahim SSN: 321-94-0309 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
87,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,47.0,NaN
88,"Thomas, Devon SSN: 326-88-5878 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
89,Mellow Yellow,Loader,10,20.0,Part-Time,No,Unsubsidized,2016-11-01 00:00:00,00:00:00,11.00,48.0,NaN
90,"Tilson, Roger SSN: 331-88-7598 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,Dunkin Donuts,cook,11,25.0,Part-Time,No,Unsubsidized,2016-12-12 00:00:00,00:00:00,12.00,49.0,NaN
92,"Toney, Demond SSN: 340-86-0136 Case: 122...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,50.0,NaN
94,"Walton, Cartier SSN: 337-86-4423 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,Kia Auto,Car Porter,12,25.0,Part-Time,No,Unsubsidized,2016-06-17 00:00:00,00:00:00,6.00,51.0,NaN
96,"Warren, Nathanel SSN: 339-94-5197 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,Walgreens,Stock Worker,10,20.0,Part-Time,No,Subsidized,2017-01-16 00:00:00,00:00:00,1.00,52.0,NaN
98,The Ark,Janitorial,10,20.0,Part-Time,No,Subsidized,2016-09-12 00:00:00,2017-01-13 00:00:00,9.00,53.0,NaN
99,"Washington, D'ante SSN: 319-90-5204 Case:...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,Macy's,Asset Protection,10,40.0,Full-Time,No,Unsubsidized,2016-11-21 00:00:00,2017-03-31 00:00:00,11.00,54.0,NaN
101,"Washington, Eric SSN: 335-04-2247 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Walgreens,Stock Worker,10,20.0,Part-Time,No,Subsidized,2016-10-10 00:00:00,00:00:00,10.00,55.0,NaN
103,"White, Barrington SSN: 345-82-1711 Case: ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
104,Luster Products,Jr Accountant,15,40.0,Full-Time,Yes,Unsubsidized,2016-09-15 00:00:00,00:00:00,9.00,56.0,NaN
105,"Whiteside, Dominique SSN: 340-86-5199 Cas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
106,Luster Products,NaN,10,40.0,Seasonal,No,Subsidized,2016-09-19 00:00:00,2016-10-07 00:00:00,9.00,57.0,NaN
107,S & C Electric,Fork Lift,15,40.0,Full-Time,Yes,Unsubsidized,2016-10-15 00:00:00,2016-11-21 00:00:00,10.00,58.0,NaN
108,"Williams, Dominique SSN: 323-86-9357 Case...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,Peacocks Foods,Warehouse,10,40.0,Full-Time,No,Unsubsidized,2016-12-23 00:00:00,00:00:00,12.00,59.0,NaN
110,"Winston, Fake SSN: Case: 11184 Prog...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
111,Fake Employer 6,Clerk,0,0.0,NaN,NaN,NaN,2016-12-28 00:00:00,00:00:00,12.00,60.0,NaN
112,Fake Employer 7,Clerk 2,0,0.0,NaN,NaN,NaN,2016-12-28 00:00:00,00:00:00,12.00,61.0,NaN
113,"Winton, Darres SSN: 357-84-4589 Case: 11...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,62.0,NaN
115,Total for :Placed into Employment,62,Total Terminations,13.0,Total Participants placed for :\nPlaced into E...,52,Average Starting Wage:,10.7945,Average Hours/Week:,34.75,NaN,NaN
116,Placed into Employment,Placed into Employment,Placed into Employment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,Total Participants,52,Total Placements:,52.0,100,Total Not Placed:,0,0,NaN,NaN,NaN,NaN
118,2017-04-10 00:00:00,Page -1 of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [78]:
sf.groupby('Status').size().to_frame()

                                                     0
Status
100                                                  1
Full-Time                                           25
Part-Time                                           14
Seasonal                                             4
Total Participants placed for :\nPlaced into Em...   1

In [20]:
sf.head()

,Employer,Job Title,Hourly Wage,Hours / Week,Status,Benefits,Placement Type,Start Date,Term. Date,Unnamed: 9,Unnamed: 10
0,Placed into Employment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Alex, Duran SSN: 318-82-2799 Case: 12249...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Corner Bakery,cook,10,40.0,Full-Time,Yes,Unsubsidized,2016-11-14 00:00:00,2016-11-14 00:00:00,11.0,1.0
3,"Alvarez, Eugene SSN: 361-08-5657 Case: 1...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Walmart,Sales Associate,10,40.0,Full-Time,No,Unsubsidized,2016-09-05 00:00:00,00:00:00,9.0,2.0

In [318]:

sf = pd.read_excel('SF_JobsReport.xls')
is_Ark = sf.Employer == 'The Ark'
#sf_profile = sf[is_not_100&is_not_part_time&is_not_seasonal&is_not_full_time]
#sf_profile[sf['Job Title'].isnull()]
#sf_profile = sf_profile.drop(sf_profile[is_Ark].index)
#sf_profile = pd.concat([pd.DataFrame(sf.iloc[1]).transpose(),sf_profile])
sf_Ark = sf[is_Ark]
sf_exp = sf[~sf['Start Date'].isnull()|is_Ark]
#sf_exp
#sf = sf.drop(sf_profile.index)
#sf= sf.drop(sf.index[[0,1]])
#sf_profile.index
#sf_profile.groupby('Job Title').size().to_frame()
#sf['profile'] = sf_profile.drop(sf_profile.index[0])
sf_exp

,Employer,Job Title,Hourly Wage,Hours / Week,Status,Benefits,Placement Type,Start Date,Term. Date,Unnamed: 9,Unnamed: 10
2,Corner Bakery,cook,10,40.0,Full-Time,Yes,Unsubsidized,2016-11-14 00:00:00,2016-11-14 00:00:00,11.00,1.0
4,Walmart,Sales Associate,10,40.0,Full-Time,No,Unsubsidized,2016-09-05 00:00:00,00:00:00,9.00,2.0
6,The Ark,NaN,10.5,0.0,NaN,NaN,NaN,2016-12-16 00:00:00,00:00:00,12.00,3.0
8,Luster Products,loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,2016-12-15 00:00:00,9.00,4.0
9,Walgreens,CLERK,10,20.0,Part-Time,No,NaN,2017-03-22 00:00:00,00:00:00,3.00,5.0
11,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,6.0
13,Greater West Town,intern,10,15.0,Seasonal,No,Subsidized,2017-02-20 00:00:00,00:00:00,2.00,7.0
15,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,8.0
17,LBP Manufacturing,NaN,11.25,40.0,Full-Time,NaN,Unsubsidized,2016-08-01 00:00:00,2016-09-02 00:00:00,8.00,9.0
18,Swisssport,Sorter,10,40.0,Full-Time,Yes,Unsubsidized,2017-01-30 00:00:00,2017-03-03 00:00:00,1.00,10.0
19,Studio Movie,Greeter,12.35,40.0,Full-Time,No,Unsubsidized,2017-03-03 00:00:00,00:00:00,3.00,11.0
21,Saint Sabina ERC,Youth Counselor,10,40.0,Full-Time,No,Unsubsidized,2016-11-14 00:00:00,00:00:00,11.00,12.0
23,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,13.0
25,LA Fitness,Program Manager,10,0.0,Full-Time,No,Unsubsidized,2016-05-23 00:00:00,00:00:00,5.00,14.0
27,Macy's,Asset Protection,10,40.0,Full-Time,No,Unsubsidized,2016-12-20 00:00:00,00:00:00,12.00,15.0
29,Luster Products,Loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,00:00:00,9.00,16.0
31,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,17.0
33,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,18.0
35,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,19.0
37,Walgreens,Stock Worker,10,25.0,Part-Time,No,Subsidized,2016-09-12 00:00:00,00:00:00,9.00,20.0
39,LA Fitness,NaN,11,0.0,Part-Time,NaN,Unsubsidized,2016-09-16 00:00:00,00:00:00,9.00,21.0
41,Hinkley Springs,Assembly Line,11,40.0,Full-Time,Yes,Unsubsidized,2016-09-20 00:00:00,2017-01-20 00:00:00,9.00,22.0
43,Luster Products,Fork Lift,11,40.0,Full-Time,Yes,Subsidized,2016-11-21 00:00:00,00:00:00,11.00,23.0
45,Walmart,Clerk,10,40.0,Full-Time,No,Unsubsidized,2016-10-10 00:00:00,00:00:00,10.00,24.0
47,Dollar Tree,Clerk,11,40.0,Full-Time,No,Unsubsidized,2016-12-05 00:00:00,00:00:00,12.00,25.0
49,The Ark,Manager,15.5,80.0,Full-Time,Yes,NaN,2016-12-16 00:00:00,00:00:00,12.00,26.0
50,The Ark,NaN,0,0.0,NaN,NaN,NaN,2016-12-16 00:00:00,00:00:00,12.00,27.0
52,Uber,driver,12,40.0,Full-Time,No,Unsubsidized,2016-09-19 00:00:00,2017-01-31 00:00:00,9.00,28.0
54,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-01-13 00:00:00,00:00:00,1.00,29.0
55,Macy's,Asset Protection,10,40.0,Seasonal,No,Unsubsidized,2016-12-05 00:00:00,2017-01-20 00:00:00,12.00,30.0
...,...,...,...,...,...,...,...,...,...,...,...
64,C.H. Robinson,Dispatcher,13,40.0,Full-Time,Yes,Unsubsidized,2016-09-09 00:00:00,00:00:00,9.00,35.0
66,Paul Cuffe,Youth Counselor,12.86,20.0,Part-Time,No,Unsubsidized,2017-01-23 00:00:00,00:00:00,1.00,36.0
68,Luster Products,Loader,10,40.0,Full-Time,No,Subsidized,2016-09-19 00:00:00,2016-11-18 00:00:00,9.00,37.0
70,St. Sabina Employment Resource Center,Youth Counselor,10,40.0,Full-Time,No,Subsidized,2016-12-05 00:00:00,00:00:00,12.00,38.0
72,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,39.0
74,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,40.0
76,St. Sabina Employment Resource Center,Receptionist,10,35.0,Full-Time,NaN,Unsubsidized,2016-11-16 00:00:00,00:00:00,11.00,41.0
78,LA Fitness,NaN,10.5,0.0,Part-Time,NaN,Unsubsidized,2016-10-08 00:00:00,00:00:00,10.00,42.0
80,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,43.0
82,Metraflex,NaN,10,40.0,Seasonal,No,Subsidized,2016-09-15 00:00:00,2016-12-16 00:00:00,9.00,44.0
83,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,45.0
85,Greater West Town,intern,10,15.0,Part-Time,No,Subsidized,2017-01-30 00:00:00,00:00:00,1.00,46.0
87,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,47.0
89,Mellow Yellow,Loader,10,20.0,Part-Time,No,Unsubsidized,2016-11-01 00:00:00,00:00:00,11.00,48.0
91,Dunkin Donuts,cook,11,25.0,Part-Time,No,Unsubsidized,2016-12-12 00:00:00,00:00:00,12.00,49.0
93,Unemployed,unemployed,0,0.0,NaN,NaN,NaN,2017-02-07 00:00:00,00:00:00,2.00,50.0
95,Kia Auto,Car Porter,12,25.0,Part-Time,No,Unsubsidized,2016-06-17 00:00:00,00:00:00,6.00,51.0
97,Walgreens,Stock Worker,10,20.0,Part-Time,No,Subsidized,2017-01-16 00:00:00,00:00:00,1.00,52.0
98,The Ark,Janitorial,10,20.0,Part-Time,No,Subsidized,2016-09-12 00:00:00,2017-01-13 00:00:00,9.00,53.0
100,Macy's,Asset Protection,10,40.0,Full-Time,No,Unsubsidized,2016-11-21 00:00:00,2017-03-31 00:00:00,11.00,54.0
102,Walgreens,Stock Worker,10,20.0,Part-Time,No,Subsidized,2016-10-10 00:00:00,00:00:00,10.00,55.0
104,Luster Products,Jr Accountant,15,40.0,Full-Time,Yes,Unsubsidized,2016-09-15 00:00:00,00:00:00,9.00,56.0
106,Luster Products,NaN,10,40.0,Seasonal,No,Subsidized,2016-09-19 00:00:00,2016-10-07 00:00:00,9.00,57.0
107,S & C Electric,Fork Lift,15,40.0,Full-Time,Yes,Unsubsidized,2016-10-15 00:00:00,2016-11-21 00:00:00,10.00,58.0
109,Peacocks Foods,Warehouse,10,40.0,Full-Time,No,Unsubsidized,2016-12-23 00:00:00,00:00:00,12.00,59.0
111,Fake Employer 6,Clerk,0,0.0,NaN,NaN,NaN,2016-12-28 00:00:00,00:00:00,12.00,60.0
112,Fake Employer 7,Clerk 2,0,0.0,NaN,NaN,NaN,2016-12-28 00:00:00,00:00:00,12.00,61.0
114,Unemployed,Unemployed,0,0.0,NaN,NaN,NaN,2017-02-06 00:00:00,00:00:00,2.00,62.0
115,Total for :Placed into Employment,62,Total Terminations,13.0,Total Participants placed for :\nPlaced into E...,52,Average Starting Wage:,10.7945,Average Hours/Week:,34.75,NaN
117,Total Participants,52,Total Placements:,52.0,100,Total Not Placed:,0,0,NaN,NaN,NaN

In [323]:
sf_exp.groupby('Employer').size().to_frame

<bound method Series.to_frame of Employer
C.H. Robinson                             1
Corner Bakery                             1
Dollar Tree                               2
Dunkin Donuts                             1
EA Sween                                  1
Fake Employer 6                           1
Fake Employer 7                           1
Greater West Town                         2
Hinkley Springs                           1
Kia Auto                                  1
LA Fitness                                3
LBP Manufacturing                         1
Luster Products                           6
Macy's                                    3
Mellow Yellow                             1
Metraflex                                 1
Norman's Bistro                           1
Paul Cuffe                                1
Peacocks Foods                            1
S & C Electric                            1
Saint Sabina ERC                          1
St. Sabina Employment Resource Center     2
Studio Movie                              1
Swisssport                                1
The Ark                                   4
Total Participants                        1
Total for :Placed into Employment         1
Uber                                      1
Unemployed                               15
Walgreens                                 4
Walmart                                   2
dtype: int64>

In [157]:
sf = pd.read_excel('SF_JobsReport.xls')
pd.DataFrame(sf.iloc[1]).transpose()

,Employer,Job Title,Hourly Wage,Hours / Week,Status,Benefits,Placement Type,Start Date,Term. Date,Unnamed: 9,Unnamed: 10
1,"Alex, Duran SSN: 318-82-2799 Case: 12249...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [336]:
sf_exp.groupby(['Employer','Hourly Wage']).size().to_frame

<bound method Series.to_frame of Employer                               Hourly Wage
C.H. Robinson                          13                     1
Corner Bakery                          10                     1
Dollar Tree                            10                     1
                                       11                     1
Dunkin Donuts                          11                     1
EA Sween                               11.5                   1
Fake Employer 6                        0                      1
Fake Employer 7                        0                      1
Greater West Town                      10                     2
Hinkley Springs                        11                     1
Kia Auto                               12                     1
LA Fitness                             10                     1
                                       10.5                   1
                                       11                     1
LBP Manufacturing                      11.25                  1
Luster Products                        10                     4
                                       11                     1
                                       15                     1
Macy's                                 10                     3
Mellow Yellow                          10                     1
Metraflex                              10                     1
Norman's Bistro                        8.5                    1
Paul Cuffe                             12.86                  1
Peacocks Foods                         10                     1
S & C Electric                         15                     1
Saint Sabina ERC                       10                     1
St. Sabina Employment Resource Center  10                     2
Studio Movie                           12.35                  1
Swisssport                             10                     1
The Ark                                0                      1
                                       10                     1
                                       10.5                   1
                                       15.5                   1
Total Participants                     Total Placements:      1
Total for :Placed into Employment      Total Terminations     1
Uber                                   12                     1
Unemployed                             0                     15
Walgreens                              10                     4
Walmart                                10                     2
dtype: int64>